### ISSUE TITLE
Error installing data on Mac OS X

### ISSUE THREAD

**Issue by meric** [honnibal/spaCy#90]
I'm on Mac OS X 10.9.4. I've used pip to install spaCy, but then ran into issues running the command to download the data. The log for the pip install is way too long so I've put it in a paste here: http://lpaste.net/140382

What do you make of this?

```
(nlp-env) ➜  nlp  python -m spacy.en.download                                                                  
/Users/Eric/Projects/nlp/nlp-env/bin/python: Error while finding spec for 'spacy.en.download' (<class 'ImportError'>: dlopen(/Users/Eric/Projects/nlp/nlp-env/lib/python3.4/site-packages/spacy/vocab.so, 2): Symbol not found: __ZTINSt8ios_base7failureE
  Referenced from: /Users/Eric/Projects/nlp/nlp-env/lib/python3.4/site-packages/spacy/vocab.so
  Expected in: flat namespace
 in /Users/Eric/Projects/nlp/nlp-env/lib/python3.4/site-packages/spacy/vocab.so)
(nlp-env) ➜  nlp  python --version
Python 3.4.3
(nlp-env) ➜  nlp  which python
/Users/Eric/Projects/nlp/nlp-env/bin/python
(nlp-env) ➜  nlp  pip freeze
Unidecode==0.04.18
cymem==1.11
murmurhash==0.24
numpy==1.9.2
plac==0.9.1
preshed==0.41
six==1.9.0
spacy==0.89
thinc==3.3
ujson==1.33
wget==2.2
```

**Comment by honnibal** [comment]
Sorry for the late reply.

This was a documentation error, which is now fixed. Try:

    python -m spacy.en.download all

**Comment by meric** [comment]
Thanks for the reply.

Looks like the issue still there though. Maybe it's like a compiled object not in the right place at the right time.
```
(nlp-env) ➜  nlp  python -m spacy.en.download all
/Users/Eric/Projects/nlp/nlp-env/bin/python: Error while finding spec for 'spacy.en.download' (<class 'ImportError'>: dlopen(/Users/Eric/Projects/nlp/nlp-env/lib/python3.4/site-packages/spacy/vocab.so, 2): Symbol not found: __ZTINSt8ios_base7failureE
  Referenced from: /Users/Eric/Projects/nlp/nlp-env/lib/python3.4/site-packages/spacy/vocab.so
  Expected in: flat namespace
 in /Users/Eric/Projects/nlp/nlp-env/lib/python3.4/site-packages/spacy/vocab.so)
```

Googling for `__ZTINSt8ios_base7failureE` yields some links about Cython.

https://gist.github.com/dpfau/1cb957dece0a8f1a4883

**Comment by honnibal** [comment]
Would you mind trying again with the new version? v0.90 is now pushed to PyPi.

**Comment by meric** [comment]
Hmm looks like the same issue.

I think the fix could be as simple as setting the environment variable `CXX=g++` in setup.py when it detects as macosx, as in  https://github.com/CoolProp/CoolProp/commit/e236d44989bb9ff64d572e514e23dd624849ce15.

I'm not sure if that's just avoiding the problem with issues with the clang compiler working with Cython though.

**Comment by honnibal** [comment]
Ah, dammit. I knew this seemed familiar.

http://stackoverflow.com/questions/28641408/how-to-tell-which-compiler-will-be-invoked-for-a-python-c-extension-in-setuptool

I'm not sure I like the solution you link. What if GCC isn't available? It seems to me that spaCy should respect the user's choice of compiler, and just set a different flag. I don't think we should be changing which compiler you use.

But, setuptools seems to offer no API to do this. I'll go and ask, thanks.

**Comment by meric** [comment]
I concur, though I don't think it's using a different compiler since g++ is symlinked to clang just with different defaults - that's what I gleaned from this link https://support.enthought.com/hc/en-us/articles/204469410-OS-X-GCC-Clang-and-Cython-in-10-9-Mavericks maybe we can change the other flags.

**Comment by honnibal** [comment]
Hmm. I thought if you installed GCC on OSX, g++ would be pointing towards actual GCC, not clang?

**Comment by meric** [comment]
```
g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```

If we don't have g++ installed I think it just symlinks to clang with some special defaults.

**Comment by honnibal** [comment]
Can you try now? I think the latest changes to setup.py should have this fixed.
